service: grapevine-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

plugins:
  - serverless-plugin-typescript

functions:
  grapevine_posts:
    handler: src/posts_get.handler
    events:
      - http:
          path: posts
          method: get
          cors: true
